import { Board, Card, Column } from "@/src/shared/types/normalized";

const now = new Date().toISOString();

export const sampleBoard: Board = {
  id: "board-1",
  title: "Product Roadmap",
  description: "A learning-focused Kanban board inspired by Linear and Trello",
  columnIds: [
    "column-backlog",
    "column-todo",
    "column-progress",
    "column-done",
  ],
  createdAt: now,
  updatedAt: now,
};

export const sampleColumns: Column[] = [
  {
    id: "column-backlog",
    boardId: "board-1",
    title: "Backlog",
    cardIds: ["card-1", "card-2"],
    color: "#64748B",
    isCollapsed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "column-todo",
    boardId: "board-1",
    title: "Todo",
    cardIds: ["card-3"],
    color: "#2563EB",
    isCollapsed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "column-progress",
    boardId: "board-1",
    title: "In Progress",
    cardIds: ["card-4"],
    color: "#F59E0B",
    isCollapsed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "column-done",
    boardId: "board-1",
    title: "Done",
    cardIds: [],
    color: "#10B981",
    isCollapsed: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleCards: Card[] = [
  {
    id: "card-1",
    boardId: "board-1",
    columnId: "column-backlog",
    title: "Design normalized state model",
    description: "Define board, column and card relationships.",
    labels: ["architecture"],
    priority: "high",
    order: 0,
    createdAt: now,
    updatedAt: now,
    isArchived: false,
  },
  {
    id: "card-2",
    boardId: "board-1",
    columnId: "column-backlog",
    title: "Plan drag-and-drop strategy",
    description: "Choose collision detection and reorder algorithm.",
    labels: ["dnd"],
    priority: "high",
    order: 1,
    createdAt: now,
    updatedAt: now,
    isArchived: false,
  },
  {
    id: "card-3",
    boardId: "board-1",
    columnId: "column-todo",
    title: "Create board shell",
    description: "Render columns and basic empty states.",
    labels: ["ui"],
    priority: "medium",
    order: 0,
    createdAt: now,
    updatedAt: now,
    isArchived: false,
  },
  {
    id: "card-4",
    boardId: "board-1",
    columnId: "column-progress",
    title: "Setup Redux Persist",
    description: "Persist selected board state.",
    labels: ["state"],
    priority: "medium",
    order: 0,
    createdAt: now,
    updatedAt: now,
    isArchived: false,
  },
];
